### ISSUE TITLE
Investigate replacement for acrn-efi-setup

### ISSUE THREAD

**Issue by rossburton** [intel/meta-acrn#16]
Are there better ways of doing this?  And if not, can we at least be sure that we're not deleting entries that should be preserved.

**Comment by ChinHuatAng** [comment]
One possible solution is to create a wic image which renames arcn.efi to the EFI fallback name bootx64.efi, here's the prototype:

https://github.com/cheeyanglee/meta-acrn/commit/adeb18af7e73539286650352f0e5f7bfe472b268

**Comment by rossburton** [comment]
Doesn't let you set options, but that might be sufficient.

**Comment by cheeyanglee** [comment]
not sure would combine systemd-boot efi and grub-efi with chain module could work to provide option to boot between native and acrn hypervisor. 

grub-efi will be the fallback EFI, during bootup it will first load grub-efi and drop to grub boot menu which offer two option, 
 - native 
   chainload bootloaderx64.efi (which is systemd-boot efi) and drop to systemd-boot menu, this will boot to native since acrn hypervisor are not loaded
 - acrn
   chainload acrn.efi, when the hypervisor is up, acrn.efi will load efi for SOS which is also bootloaderx64.efi and drop to systemd-boot menu

here is the prototype: 
https://github.com/cheeyanglee/meta-acrn/tree/wic_wks

**Comment by moto-timo** [comment]
Build and run time tested wic_wks. This is a superior solution.

**Comment by saininav** [comment]
@cheeyanglee  please raise pull request

**Comment by saininav** [comment]
Fix in available in master. closing this.
